### ISSUE TITLE
Does BrowserUp-proxy supports HTTP H2 protocol applications?

### ISSUE THREAD

**Issue by csharsha** [browserup/browserup-proxy#243]
Hi,

We have web application built on HTTP H2 protocol, but when we use BrowserUp proxy and browse the application all the web requests are using HTTP 1.1 protocol. When the application is browsed without BrowserUp, we are able to see all the requests as HTTP H2. Does BrowserUp proxy support only HTTP 1.1 protocol?

See the screenshots of Chrome F12 Devtool for both the scenarios.

Application navigated without BrowserUp
![WithHTTP_H2_Protocol](https://user-images.githubusercontent.com/3316171/76630084-6cd19c00-6565-11ea-96e0-d4388c68befc.jpg)

Application navigated using BrowserUp proxy
![WithHTTP_1 1_FromBrowserMob](https://user-images.githubusercontent.com/3316171/76630113-765b0400-6565-11ea-8c69-204013acfde9.jpg)

**Comment by ericbeland** [comment]
We originally thought we got this for free when our LittleProxy dependency updated to the latest Netty. It turns out this actually required much more, and when we dug in to littleproxy, realized it would take a littleproxy rewrite of that dependency. We are currently in-flight with a rewrite to get HTTP going. We are going to use an MITMProxy fork and make our API work through that.

**Comment by ericbeland** [comment]
I'm closing this for now while we get the rewrite out.

**Comment by aliowka** [comment]
Hi, any expectations on that? 
Thanks!
