### ISSUE TITLE
Hi all! A couple of questions about your project

### ISSUE THREAD

**Issue by s-belichenko** [browserup/browserup-proxy#90]
What about removing the Via header from requests? Original BMP does not know how to do it.
What about displaying CONNECT method in HAR? Original BMP does not know how to do it too.

**Comment by ericbeland** [comment]
Hi @s-belichenko. Some questions on what you're looking for. The har should capture connect time. Are you instead asking about something slightly different, like capturing traffic into the har at the protocol level instead of the http layer?  

There's an issue on the original proxy repo that I see you've referenced here: https://github.com/lightbody/browsermob-proxy/issues/213

In it, jekh gives an example of how to override this in java embedded mode using an override to the internal littleproxy. His example shows how to override headers on the request, but not the response. If both were implemented I imagine this would work. Is this different than what you are looking for, or you tried also implementing the filter on the response, and that didn't work?

**Comment by ericbeland** [comment]
@s-belichenko Let us know if you have more questions. Closing for now.
